services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    <<: &service
      image: node:18
      working_dir: /src
      volumes:
        - .:/src
        - node-modules:/src/node_modules
        - yarn-cache:/src/.yarn-cache
      environment:
        - YARN_CACHE_FOLDER=/src/.yarn-cache
      env_file: .env
    command: ["yarn", "server"]
    ports:
      - "3001:3001"

  client:
    command: ["yarn", "client"]
    ports:
      - "3000:5173"
    <<: *service

volumes:
  node-modules:
  yarn-cache:
  postgres-data:
